<!-- legacy -->
<script type="text/javascript" src="js/settings.js"></script>
<script type="text/javascript" src="js/supported-coins-list.js"></script>
<script type="text/javascript" src="js/dev.js"></script>
<script type="text/javascript" src="js/lang/en.js"></script>
<script type="text/javascript" src="js/iguana-add-coin-list.js"></script>
<!-- angular -->
<script type="text/javascript" src="js/angular/angular.min.js"></script>
<script type="text/javascript" src="js/angular/angular-ui-router.min.js"></script>
<script type="text/javascript" src="js/angular/angular-sanitize.min.js"></script>
<script type="text/javascript" src="js/angular/angular-animate.js"></script>
<script type="text/javascript" src="js/angular/angular-storage.min.js"></script>
<script type="text/javascript" src="js/angular/angular-clipboard.js"></script>
<script type="text/javascript" src="js/angular/jquery.min.js"></script>
<!-- libs -->
<script type="text/javascript" src="js/libs/ui-bootstrap/ui-bootstrap.js"></script>
<script type="text/javascript" src="js/libs/kjua-0.1.1.min.js"></script>
<script type="text/javascript" src="js/libs/bootstrap.min.js"></script>
<script type="text/javascript" src="js/app.js"></script>
<!-- directives -->
<script type="text/javascript" src="js/directives/spinner.js"></script>
<script type="text/javascript" src="js/directives/numberOnly.js"></script>
<script type="text/javascript" src="js/directives/appTitle.js"></script>
<!-- filters -->
<script type="text/javascript" src="js/filters/decimalPlacesFormat.js"></script>
<script type="text/javascript" src="js/filters/lang.js"></script>
<!-- services -->
<script type="text/javascript" src="js/services/storage.js"></script>
<script type="text/javascript" src="js/services/rates.js"></script>
<script type="text/javascript" src="js/services/auth.js"></script>
<script type="text/javascript" src="js/services/datetime.js"></script>
<script type="text/javascript" src="js/services/syncStatus.js"></script>
<script type="text/javascript" src="js/services/message.js"></script>
<script type="text/javascript" src="js/services/passPhraseGenerator.js"></script>
<script type="text/javascript" src="js/services/util.js"></script>
<script type="text/javascript" src="js/services/api.js"></script>
<!-- controllers -->
<script type="text/javascript" src="js/controllers/loginController.js"></script>
<script type="text/javascript" src="js/controllers/signupController.js"></script>
<script type="text/javascript" src="js/controllers/dashboardController.js"></script>
<script type="text/javascript" src="js/controllers/settingsController.js"></script>
<script type="text/javascript" src="js/controllers/topMenuController.js"></script>
<!-- modal -->
<script type="text/javascript" src="js/controllers/addCoinModalController.js"></script>
<script type="text/javascript" src="js/controllers/addCoinLoginModalController.js"></script>
<script type="text/javascript" src="js/controllers/receiveCoinModalController.js"></script>
<script type="text/javascript" src="js/controllers/sendCoinModalController.js"></script>
<script type="text/javascript" src="js/controllers/sendCoinPassphraseModalController.js"></script>
<script type="text/javascript" src="js/controllers/messageController.js"></script>